// Villes du Maroc (Sprint 30, point 6) — liste statique pour la fiche
// bureau (menu déroulant), pas une table de référence séparée : rien ici
// n'est relu ailleurs dans l'application, pur confort de saisie.
export const VILLES_MAROC = [
  "Agadir",
  "Al Hoceïma",
  "Assilah",
  "Azrou",
  "Béni Mellal",
  "Berkane",
  "Berrechid",
  "Bouskoura",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Fquih Ben Salah",
  "Guelmim",
  "Ifrane",
  "Kénitra",
  "Khemisset",
  "Khénifra",
  "Khouribga",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Meknès",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Oued Zem",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Settat",
  "Sidi Bennour",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirate",
  "Tan-Tan",
  "Tanger",
  "Taourirt",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
  "Tiflet",
  "Tiznit",
  "Youssoufia",
] as const;
