-- ============================================================
-- Sinistria-VV — 0013 : référentiel Marques & Modèles (Sprint 14)
--
-- Reprend le référentiel de l'ancien système (sélecteur marque -> modèle,
-- suggestion de la valeur à neuf) avec, cette fois, des droits appliqués
-- par la base et non seulement par l'interface :
--   - lecture : tout profil existant ET actif (est_profil_actif(), 0012) ;
--   - ajout d'une marque ou d'un modèle (« à la volée ») : tout profil actif,
--     mais un modèle ajouté par un non-éditeur ne peut pas porter de prix VN ;
--   - renommer, supprimer, éditer vn_reference : responsable et au-dessus
--     (current_role_niveau() >= 5, nul pour un profil inactif ou absent).
--
-- Unicité insensible à la casse, aux espaces de bord : comme la
-- normalisation (trim + minuscules) de l'ancien système.
--
-- Les colonnes vv_calculations.marque / .modele restent du texte libre
-- (instantané de ce qui a été saisi, pas de clé étrangère, pas de reprise).
--
-- Seed : 44 marques / 322 modèles, générés par programme depuis la
-- constante VSEED de l'ancien Index.html (aucun prix VN dans la source).
-- ============================================================

create table vehicule_marques (
  id uuid primary key default gen_random_uuid(),
  nom text not null unique,
  constraint vehicule_marques_nom_propre check (nom = btrim(nom) and nom <> '')
);
create unique index vehicule_marques_nom_norm on vehicule_marques (lower(btrim(nom)));

create table vehicule_modeles (
  id uuid primary key default gen_random_uuid(),
  marque_id uuid not null references vehicule_marques(id) on delete cascade,
  nom text not null,
  vn_reference numeric(12,2),
  unique (marque_id, nom),
  constraint vehicule_modeles_nom_propre check (nom = btrim(nom) and nom <> ''),
  constraint vehicule_modeles_vn_positive check (vn_reference is null or vn_reference > 0)
);
create unique index vehicule_modeles_marque_nom_norm on vehicule_modeles (marque_id, lower(btrim(nom)));

alter table vehicule_marques enable row level security;
alter table vehicule_modeles enable row level security;

-- Lecture
create policy "vehicule_marques_select" on vehicule_marques
  for select using (est_profil_actif());
create policy "vehicule_modeles_select" on vehicule_modeles
  for select using (est_profil_actif());

-- Ajout à la volée : tout profil actif
create policy "vehicule_marques_insert" on vehicule_marques
  for insert with check (est_profil_actif());
create policy "vehicule_modeles_insert" on vehicule_modeles
  for insert with check (
    est_profil_actif()
    and (vn_reference is null or current_role_niveau() >= role_niveau('responsable'))
  );

-- Modification et suppression : responsable et au-dessus
create policy "vehicule_marques_update" on vehicule_marques
  for update using (current_role_niveau() >= role_niveau('responsable'))
  with check (current_role_niveau() >= role_niveau('responsable'));
create policy "vehicule_marques_delete" on vehicule_marques
  for delete using (current_role_niveau() >= role_niveau('responsable'));
create policy "vehicule_modeles_update" on vehicule_modeles
  for update using (current_role_niveau() >= role_niveau('responsable'))
  with check (current_role_niveau() >= role_niveau('responsable'));
create policy "vehicule_modeles_delete" on vehicule_modeles
  for delete using (current_role_niveau() >= role_niveau('responsable'));

-- Seed
insert into vehicule_marques (nom) values
  ('Renault'),
  ('Dacia'),
  ('Peugeot'),
  ('Citroen'),
  ('DS'),
  ('Volkswagen'),
  ('Audi'),
  ('BMW'),
  ('Mercedes'),
  ('Toyota'),
  ('Hyundai'),
  ('Kia'),
  ('Ford'),
  ('Opel'),
  ('Fiat'),
  ('Alfa'),
  ('Nissan'),
  ('Honda'),
  ('Suzuki'),
  ('Mazda'),
  ('Mitsubishi'),
  ('Subaru'),
  ('Seat'),
  ('Skoda'),
  ('Volvo'),
  ('Jeep'),
  ('Land Rover'),
  ('Porsche'),
  ('Lexus'),
  ('Tesla'),
  ('Mini'),
  ('Chevrolet'),
  ('MG'),
  ('BYD'),
  ('Geely'),
  ('Chery'),
  ('Changan'),
  ('Haval'),
  ('JAC'),
  ('SsangYong'),
  ('Mahindra'),
  ('Great Wall'),
  ('DFSK'),
  ('Foton')
on conflict do nothing;

insert into vehicule_modeles (marque_id, nom)
select m.id, s.modele
from (values
  ('Renault', 'Clio'),
  ('Renault', 'Megane'),
  ('Renault', 'Captur'),
  ('Renault', 'Kadjar'),
  ('Renault', 'Austral'),
  ('Renault', 'Arkana'),
  ('Renault', 'Kangoo'),
  ('Renault', 'Express'),
  ('Renault', 'Trafic'),
  ('Renault', 'Master'),
  ('Renault', 'Scenic'),
  ('Renault', 'Twingo'),
  ('Renault', 'Symbol'),
  ('Renault', 'Koleos'),
  ('Renault', 'Espace'),
  ('Dacia', 'Logan'),
  ('Dacia', 'Sandero'),
  ('Dacia', 'Duster'),
  ('Dacia', 'Spring'),
  ('Dacia', 'Jogger'),
  ('Dacia', 'Lodgy'),
  ('Dacia', 'Dokker'),
  ('Peugeot', '108'),
  ('Peugeot', '208'),
  ('Peugeot', '2008'),
  ('Peugeot', '308'),
  ('Peugeot', '3008'),
  ('Peugeot', '408'),
  ('Peugeot', '508'),
  ('Peugeot', '5008'),
  ('Peugeot', 'Partner'),
  ('Peugeot', 'Expert'),
  ('Peugeot', 'Boxer'),
  ('Peugeot', 'Rifter'),
  ('Citroen', 'C1'),
  ('Citroen', 'C3'),
  ('Citroen', 'C3 Aircross'),
  ('Citroen', 'C4'),
  ('Citroen', 'C4 X'),
  ('Citroen', 'C5 Aircross'),
  ('Citroen', 'C5 X'),
  ('Citroen', 'Berlingo'),
  ('Citroen', 'Jumpy'),
  ('Citroen', 'Jumper'),
  ('Citroen', 'Ami'),
  ('Citroen', 'SpaceTourer'),
  ('DS', 'DS 3'),
  ('DS', 'DS 4'),
  ('DS', 'DS 7'),
  ('DS', 'DS 9'),
  ('Volkswagen', 'Up'),
  ('Volkswagen', 'Polo'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'T-Roc'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'ID.3'),
  ('Volkswagen', 'ID.4'),
  ('Volkswagen', 'Caddy'),
  ('Volkswagen', 'Transporter'),
  ('Volkswagen', 'Crafter'),
  ('Audi', 'A1'),
  ('Audi', 'A3'),
  ('Audi', 'A4'),
  ('Audi', 'A5'),
  ('Audi', 'A6'),
  ('Audi', 'Q2'),
  ('Audi', 'Q3'),
  ('Audi', 'Q5'),
  ('Audi', 'Q7'),
  ('Audi', 'Q8'),
  ('Audi', 'e-tron'),
  ('BMW', 'Serie 1'),
  ('BMW', 'Serie 2'),
  ('BMW', 'Serie 3'),
  ('BMW', 'Serie 4'),
  ('BMW', 'Serie 5'),
  ('BMW', 'Serie 7'),
  ('BMW', 'X1'),
  ('BMW', 'X2'),
  ('BMW', 'X3'),
  ('BMW', 'X4'),
  ('BMW', 'X5'),
  ('BMW', 'X6'),
  ('BMW', 'i3'),
  ('BMW', 'i4'),
  ('BMW', 'iX'),
  ('Mercedes', 'Classe A'),
  ('Mercedes', 'Classe B'),
  ('Mercedes', 'Classe C'),
  ('Mercedes', 'Classe E'),
  ('Mercedes', 'Classe S'),
  ('Mercedes', 'GLA'),
  ('Mercedes', 'GLB'),
  ('Mercedes', 'GLC'),
  ('Mercedes', 'GLE'),
  ('Mercedes', 'GLS'),
  ('Mercedes', 'Citan'),
  ('Mercedes', 'Vito'),
  ('Mercedes', 'Sprinter'),
  ('Toyota', 'Aygo'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'C-HR'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Hilux'),
  ('Toyota', 'Land Cruiser'),
  ('Toyota', 'Prius'),
  ('Toyota', 'Camry'),
  ('Toyota', 'Proace'),
  ('Hyundai', 'i10'),
  ('Hyundai', 'i20'),
  ('Hyundai', 'i30'),
  ('Hyundai', 'Bayon'),
  ('Hyundai', 'Kona'),
  ('Hyundai', 'Tucson'),
  ('Hyundai', 'Santa Fe'),
  ('Hyundai', 'Elantra'),
  ('Hyundai', 'Accent'),
  ('Kia', 'Picanto'),
  ('Kia', 'Rio'),
  ('Kia', 'Ceed'),
  ('Kia', 'Stonic'),
  ('Kia', 'Niro'),
  ('Kia', 'Sportage'),
  ('Kia', 'Sorento'),
  ('Kia', 'EV6'),
  ('Ford', 'Fiesta'),
  ('Ford', 'Focus'),
  ('Ford', 'Puma'),
  ('Ford', 'Kuga'),
  ('Ford', 'Explorer'),
  ('Ford', 'EcoSport'),
  ('Ford', 'Ranger'),
  ('Ford', 'Transit'),
  ('Ford', 'Tourneo'),
  ('Opel', 'Corsa'),
  ('Opel', 'Astra'),
  ('Opel', 'Mokka'),
  ('Opel', 'Crossland'),
  ('Opel', 'Grandland'),
  ('Opel', 'Combo'),
  ('Opel', 'Vivaro'),
  ('Opel', 'Zafira'),
  ('Fiat', '500'),
  ('Fiat', '500X'),
  ('Fiat', '500L'),
  ('Fiat', 'Panda'),
  ('Fiat', 'Tipo'),
  ('Fiat', 'Punto'),
  ('Fiat', 'Doblo'),
  ('Fiat', 'Fiorino'),
  ('Fiat', 'Ducato'),
  ('Alfa', 'Giulietta'),
  ('Alfa', 'Giulia'),
  ('Alfa', 'Stelvio'),
  ('Alfa', 'Tonale'),
  ('Alfa', 'MiTo'),
  ('Nissan', 'Micra'),
  ('Nissan', 'Juke'),
  ('Nissan', 'Qashqai'),
  ('Nissan', 'X-Trail'),
  ('Nissan', 'Leaf'),
  ('Nissan', 'Navara'),
  ('Nissan', 'Patrol'),
  ('Nissan', 'Townstar'),
  ('Honda', 'Jazz'),
  ('Honda', 'Civic'),
  ('Honda', 'HR-V'),
  ('Honda', 'ZR-V'),
  ('Honda', 'CR-V'),
  ('Honda', 'City'),
  ('Honda', 'Accord'),
  ('Suzuki', 'Ignis'),
  ('Suzuki', 'Swift'),
  ('Suzuki', 'Baleno'),
  ('Suzuki', 'Vitara'),
  ('Suzuki', 'S-Cross'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'Alto'),
  ('Mazda', 'Mazda 2'),
  ('Mazda', 'Mazda 3'),
  ('Mazda', 'Mazda 6'),
  ('Mazda', 'CX-3'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'CX-5'),
  ('Mazda', 'CX-60'),
  ('Mazda', 'MX-5'),
  ('Mitsubishi', 'Attrage'),
  ('Mitsubishi', 'ASX'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Mitsubishi', 'Outlander'),
  ('Mitsubishi', 'Pajero'),
  ('Mitsubishi', 'L200'),
  ('Mitsubishi', 'Space Star'),
  ('Subaru', 'Impreza'),
  ('Subaru', 'XV'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Outback'),
  ('Subaru', 'WRX'),
  ('Seat', 'Mii'),
  ('Seat', 'Ibiza'),
  ('Seat', 'Arona'),
  ('Seat', 'Leon'),
  ('Seat', 'Ateca'),
  ('Seat', 'Tarraco'),
  ('Skoda', 'Fabia'),
  ('Skoda', 'Scala'),
  ('Skoda', 'Octavia'),
  ('Skoda', 'Superb'),
  ('Skoda', 'Kamiq'),
  ('Skoda', 'Karoq'),
  ('Skoda', 'Kodiaq'),
  ('Skoda', 'Enyaq'),
  ('Volvo', 'S60'),
  ('Volvo', 'S90'),
  ('Volvo', 'V60'),
  ('Volvo', 'V90'),
  ('Volvo', 'XC40'),
  ('Volvo', 'XC60'),
  ('Volvo', 'XC90'),
  ('Volvo', 'EX30'),
  ('Volvo', 'EX40'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Compass'),
  ('Jeep', 'Cherokee'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Wrangler'),
  ('Jeep', 'Gladiator'),
  ('Jeep', 'Avenger'),
  ('Land Rover', 'Defender'),
  ('Land Rover', 'Discovery'),
  ('Land Rover', 'Discovery Sport'),
  ('Land Rover', 'Range Rover'),
  ('Land Rover', 'Range Rover Evoque'),
  ('Land Rover', 'Range Rover Sport'),
  ('Land Rover', 'Range Rover Velar'),
  ('Porsche', '911'),
  ('Porsche', '718'),
  ('Porsche', 'Cayenne'),
  ('Porsche', 'Macan'),
  ('Porsche', 'Panamera'),
  ('Porsche', 'Taycan'),
  ('Lexus', 'UX'),
  ('Lexus', 'NX'),
  ('Lexus', 'RX'),
  ('Lexus', 'LX'),
  ('Lexus', 'IS'),
  ('Lexus', 'ES'),
  ('Lexus', 'LBX'),
  ('Tesla', 'Model 3'),
  ('Tesla', 'Model S'),
  ('Tesla', 'Model X'),
  ('Tesla', 'Model Y'),
  ('Mini', 'Mini 3 portes'),
  ('Mini', 'Mini 5 portes'),
  ('Mini', 'Clubman'),
  ('Mini', 'Countryman'),
  ('Mini', 'Aceman'),
  ('Chevrolet', 'Spark'),
  ('Chevrolet', 'Aveo'),
  ('Chevrolet', 'Cruze'),
  ('Chevrolet', 'Groove'),
  ('Chevrolet', 'Captiva'),
  ('Chevrolet', 'Silverado'),
  ('MG', 'MG3'),
  ('MG', 'MG4'),
  ('MG', 'MG5'),
  ('MG', 'ZS'),
  ('MG', 'HS'),
  ('MG', 'Marvel R'),
  ('BYD', 'Dolphin'),
  ('BYD', 'Atto 3'),
  ('BYD', 'Seal'),
  ('BYD', 'Han'),
  ('BYD', 'Tang'),
  ('BYD', 'Song'),
  ('Geely', 'Coolray'),
  ('Geely', 'Azkarra'),
  ('Geely', 'Emgrand'),
  ('Geely', 'Okavango'),
  ('Geely', 'Monjaro'),
  ('Chery', 'Tiggo 2'),
  ('Chery', 'Tiggo 4'),
  ('Chery', 'Tiggo 7'),
  ('Chery', 'Tiggo 8'),
  ('Chery', 'Arrizo 5'),
  ('Changan', 'Alsvin'),
  ('Changan', 'CS35'),
  ('Changan', 'CS55'),
  ('Changan', 'CS75'),
  ('Changan', 'Eado'),
  ('Changan', 'Uni-T'),
  ('Haval', 'Jolion'),
  ('Haval', 'M6'),
  ('Haval', 'H6'),
  ('Haval', 'Dargo'),
  ('JAC', 'J3'),
  ('JAC', 'J7'),
  ('JAC', 'S2'),
  ('JAC', 'S3'),
  ('JAC', 'JS4'),
  ('SsangYong', 'Tivoli'),
  ('SsangYong', 'Korando'),
  ('SsangYong', 'Rexton'),
  ('SsangYong', 'Musso'),
  ('SsangYong', 'Torres'),
  ('Mahindra', 'XUV300'),
  ('Mahindra', 'XUV700'),
  ('Mahindra', 'Scorpio'),
  ('Mahindra', 'Bolero'),
  ('Mahindra', 'Thar'),
  ('Great Wall', 'Steed'),
  ('Great Wall', 'Wingle'),
  ('Great Wall', 'Poer'),
  ('DFSK', 'Glory'),
  ('DFSK', 'C37'),
  ('DFSK', 'Seren 3'),
  ('Foton', 'Tunland'),
  ('Foton', 'Sauvana'),
  ('Foton', 'View')
) as s(marque, modele)
join vehicule_marques m on m.nom = s.marque
on conflict do nothing;

-- Garde-fou : la migration entière est annulée si le seed n'est pas exact.
do $$
declare nb_marques int; nb_modeles int;
begin
  select count(*) into nb_marques from vehicule_marques;
  select count(*) into nb_modeles from vehicule_modeles;
  if nb_marques <> 44 or nb_modeles <> 322 then
    raise exception 'Seed référentiel inexact : % marques / % modèles (attendu 44 / 322)', nb_marques, nb_modeles;
  end if;
end $$;
